const loginMessage = {
  type: 'template',
  altText: '請先登入以取得個人資訊',
  template: {
    type: 'buttons',
    title: '系統登入',
    text: '登入系統後即代表您同意將使用者資訊儲存於伺服器中, 以利後續服務的查詢',
    actions: [{
      type: 'postback',
      label: '登入',
      courseData: 'login',
    },
    ],
  },
};

const loginNotifyMessage = [
  { type: 'text', text: '請輸入您的學號與密碼\n格式如下' },
  { type: 'text', text: 'C107123456\n123456' },
];

let courseMessage = '';
const setCourseMessage = courseData => new Promise((resolve, reject) => {
  courseMessage = {
    type: 'flex',
    altText: '個人課表',
    contents: {
      type: 'carousel',
      contents: [{
        type: 'bubble',
        styles: {
          footer: {
            separator: true,
          },
        },
        body: {
          type: 'box',
          layout: 'vertical',
          contents: [
            {
              type: 'text',
              text: '星期一',
              weight: 'bold',
              size: 'xl',
              margin: 'sm',
              color: '#457E9B',
            },
            {
              type: 'separator',
              margin: 'xxl',
            },
            {
              type: 'box',
              layout: 'vertical',
              margin: 'xxl',
              spacing: 'sm',
              contents: [{
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第一節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[1],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第二節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[9],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第三節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[17],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第四節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[25],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第五節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[41],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第六節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[49],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第七節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[57],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第八節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'separator',
                  margin: 'xxl',
                },
                {
                  type: 'text',
                  text: courseData[65],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'separator',
                margin: 'xxl',
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第九節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[73],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第十節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[81],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第十一節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[89],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第十二節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[97],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第十三節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[105],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              ],
            },
            {
              type: 'separator',
              margin: 'xxl',
            },
          ],
        },
      }, {
        type: 'bubble',
        styles: {
          footer: {
            separator: true,
          },
        },
        body: {
          type: 'box',
          layout: 'vertical',
          contents: [
            {
              type: 'text',
              text: '星期二',
              weight: 'bold',
              size: 'xl',
              margin: 'sm',
              color: '#457E9B',
            },
            {
              type: 'separator',
              margin: 'xxl',
            },
            {
              type: 'box',
              layout: 'vertical',
              margin: 'xxl',
              spacing: 'sm',
              contents: [{
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第一節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[2],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第二節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[10],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第三節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[18],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第四節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[26],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第五節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[42],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第六節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[50],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第七節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[58],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第八節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[66],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'separator',
                margin: 'xxl',
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第九節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[74],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第十節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[82],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第十一節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[90],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第十二節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[98],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第十三節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[106],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              ],
            },
            {
              type: 'separator',
              margin: 'xxl',
            },
          ],
        },
      }, {
        type: 'bubble',
        styles: {
          footer: {
            separator: true,
          },
        },
        body: {
          type: 'box',
          layout: 'vertical',
          contents: [
            {
              type: 'text',
              text: '星期三',
              weight: 'bold',
              size: 'xl',
              margin: 'sm',
              color: '#457E9B',
            },
            {
              type: 'separator',
              margin: 'xxl',
            },
            {
              type: 'box',
              layout: 'vertical',
              margin: 'xxl',
              spacing: 'sm',
              contents: [{
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第一節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[3],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第二節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[11],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第三節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[19],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第四節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[27],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第五節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[43],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第六節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[51],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第七節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[59],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第八節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[67],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'separator',
                margin: 'xxl',
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第九節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[75],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第十節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[83],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第十一節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[91],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第十二節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[99],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第十三節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[107],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              ],
            },
            {
              type: 'separator',
              margin: 'xxl',
            },
          ],
        },
      },{
        type: 'bubble',
        styles: {
          footer: {
            separator: true,
          },
        },
        body: {
          type: 'box',
          layout: 'vertical',
          contents: [
            {
              type: 'text',
              text: '星期四',
              weight: 'bold',
              size: 'xl',
              margin: 'sm',
              color: '#457E9B',
            },
            {
              type: 'separator',
              margin: 'xxl',
            },
            {
              type: 'box',
              layout: 'vertical',
              margin: 'xxl',
              spacing: 'sm',
              contents: [{
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第一節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[4],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第二節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[12],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第三節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[20],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第四節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[28],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第五節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[44],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第六節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[52],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第七節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[60],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第八節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[68],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'separator',
                margin: 'xxl',
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第九節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[76],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第十節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[84],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第十一節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[92],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第十二節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[100],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第十三節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[108],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              ],
            },
            {
              type: 'separator',
              margin: 'xxl',
            },
          ],
        },
      },{
        type: 'bubble',
        styles: {
          footer: {
            separator: true,
          },
        },
        body: {
          type: 'box',
          layout: 'vertical',
          contents: [
            {
              type: 'text',
              text: '星期五',
              weight: 'bold',
              size: 'xl',
              margin: 'sm',
              color: '#457E9B',
            },
            {
              type: 'separator',
              margin: 'xxl',
            },
            {
              type: 'box',
              layout: 'vertical',
              margin: 'xxl',
              spacing: 'sm',
              contents: [{
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第一節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[5],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第二節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[13],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第三節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[21],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第四節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[29],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第五節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[45],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第六節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[53],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第七節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[61],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第八節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[69],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'separator',
                margin: 'xxl',
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第九節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[77],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第十節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[85],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第十一節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[93],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第十二節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[101],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              {
                type: 'box',
                layout: 'horizontal',
                contents: [{
                  type: 'text',
                  text: '第十三節',
                  size: 'sm',
                  color: '#555555',
                  flex: 0,
                },
                {
                  type: 'text',
                  text: courseData[109],
                  size: 'sm',
                  color: '#111111',
                  align: 'end',
                },
                ],
              },
              ],
            },
            {
              type: 'separator',
              margin: 'xxl',
            },
          ],
        },
      }],
    },
  };
  resolve(courseMessage);
});


module.exports.loginMessage = loginMessage;
module.exports.loginNotifyMessage = loginNotifyMessage;
module.exports.courseMessage = courseMessage;
module.exports.setCourseMessage = setCourseMessage;
